name: CI React Docker

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Build da aplicação React
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Dependências
        run: npm install

      - name: Build do Projeto
        run: npm run build

  # Job 2: Construção e Push da Imagem Docker
  docker-build:
    runs-on: ubuntu-latest
    needs: build-react # Garante que o build do React passe antes de começar
    steps:
      - uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use Secrets para segurança
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da Imagem Docker
        run: docker build -t fiecpa2026 .

      - name: Tag e Push da Imagem
        run: |
          docker tag fiecpa2026 ${{ secrets.DOCKER_USERNAME }}/fiecpa2026:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fiecpa2026:latest

  # Job 3: Rodando na AWS
  deploy-ec2:
    runs-on: [self-hosted, windows] # Especifica a tag do runner Windows
    needs: docker-build
    if: github.event_name == 'push'
    defaults:
      run:
        shell: powershell # Garante o uso do PowerShell nativo do Windows
    steps:
      - name: Atualizar e Subir Container do Backend no Windows
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fieclab-backend:latest
          
          # Para e remove o container caso ele já exista (sem quebrar a pipeline se não existir)
          if (docker ps -a --format '{{.Names}}' | Select-String "^fieclab-backend$") {
              docker stop fieclab-backend
              docker rm fieclab-backend
          }
          
          # Sobe o novo container
          docker run -d `
            --name fieclab-backend `
            --restart always `
            -p 8080:8080 `
            ${{ secrets.DOCKER_USERNAME }}/fieclab-backend:latest
